version: "3.8"
services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
      - MONGO_INITDB_DATABASE=housenumbers
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secretpassword
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_URL=mongodb://mongoadmin:secretpassword@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongoadmin:secretpassword@mongo:27017/housenumbers?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo-data: 